server:
  port: 0

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

security:
  oauth2:
    client:
      client-id: productcomposite
      client-secret: acmesecret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      grant-type: client_credentials
      scope: webshop
      authorities: ROLE_CLIENT
    resource:
      user-info-uri: http://localhost:9999/uaa/user

logging:
  level:
    se.callista: INFO
    
    
spring:
  rabbitmq:
    username: sambitc
    password: mindfire